---
- hosts: local  
  become: yes
  roles:
    - jdauphant.vagrant
    - geerlingguy.git
    - tekniqueltd.oracle-java
    - role: jdauphant.sublimetext
      sublimetext_build:  3083
  vars:
    vagrant_version: 2.0.1
    java_version: 8

