---
- hosts: remote 
  become: yes
  roles:
    - jdauphant.vagrant
    - geerlingguy.git
    - tekniqueltd.oracle-java
    - wtanaka.chrome
    - role: jdauphant.sublimetext
      sublimetext_build:  3083
    - jackl0phty.nmap
    - gantsign.maven
    - shelleg.gradle
    - daniel-rhoades.tomcat
     
  vars:
    vagrant_version: 2.0.1
    java_version: 8

